# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build_my_app do
    build_app(
      project: "ContinuousIntegrationDemo.xcodeproj",
      configuration: "Debug",
      scheme: "ContinuousIntegrationDemo",
      silent: true,
      clean: true,
      destination: "platform=iOS Simulator,name=iPhone 15",
      skip_archive: true,
      skip_package_ipa: true
    )
  end
  
  lane :test do
    # scan(
    #   project: "ContinuousIntegrationDemo.xcodeproj",
    #   scheme: "ContinuousIntegrationDemoTests",
    #   clean: true,
    #   configuration: "Debug",
    #   devices: ["iPhone 15"],
    #   prelaunch_simulator: true,
    #   ensure_devices_found: true
    # )
    sh("cd .. && xcodebuild -project ContinuousIntegrationDemo.xcodeproj -scheme ContinuousIntegrationDemoTests -destination 'platform=iOS Simulator,name=iPhone 15' -sdk iphonesimulator test")
  end

  before_all do
    puts "Starting lanes 🛫"
  end
  
  after_all do |lane|
    puts "🛬 Get some coffee now ☕️"
  end
end
