# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build do
    # fastlane: build
  end
  
  lane :test_app do
    scan(
      project: "ContinuousIntegrationDemo.xcodeproj",
      scheme: "ContinuousIntegrationDemoTests",
      clean: true,
      configuration: "Debug",
      devices: ["iPhone 15 Pro (17.5)"],
      prelaunch_simulator: true,
      ensure_devices_found: true
    )
  end

  before_all do
    puts "Starting lanes 🛫"
  end

  after_all do |lane|
    puts "🛬 Get some cofee now ☕️"
  end
end
