name: Build and Tests

on:
  push:
    branches:
      - master
      - feature/ci
  pull_request:
    branches:
      - master
jobs:
  # Build:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/setup
  #     - name: Build the app
  #       run: bundle exec fastlane build
  Tests:
    # needs: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: xcrun simctl list devices --json
      - name: Test the app
        run: xcodebuild -project ContinuousIntegrationDemo.xcodeproj -scheme ContinuousIntegrationDemoTests -destination "platform=iOS Simulator,name=iPhone 15" -sdk iphonesimulator test
