name: Build and Tests

on:
  push:
    branches:
      - main
      - feature/ci
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Install bundler deps
        run: bundle install
      - name: Build the app
        run: bundle exec fastlane build_my_app
  Tests:
    needs: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Install bundler deps
        run: bundle install
      - name: Test the app
        run: bundle exec fastlane test
