name: Build and Tests

on:
  push:
    branches:
      - master
      - feature/ci
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Build the app
        run: bundle exec fastlane build
  # Tests:
  #   needs: Build
  #   runs-on: macos-latest
  #   steps:
  #     - name: Test the app
  #       run: bundle exec fastlane test
