name: Build and Tests

on:
  push:
    branches:
      - main
      - feature/ci
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action
      - name: Build the app
        run: bundle exec fastlane build_my_app
  Tests:
    needs: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action
      - name: Test the app
        run: bundle exec fastlane test
